### ISSUE TITLE
初始化两次请求问题

### ISSUE THREAD

**Issue by 317482454** [miaoyaoyao/AngularJs-UI#2]
平常情况下使用不会出现这个问题，如果我根据条件再次加载数据，当前页码在6，我需要变成1的时候就会触发2次请求，看了源码里面有判断，但是还是加载了2次，我的解决方法如下：
 if (oldValue.split(' ')[1] != "undefined" && oldValue.split(' ')[1] == newValue.split(' ')[1])return;
页面首次加载oldValue.split(' ')[1] 的值是undefined
大大使用了oldValue和newValue来判断，按照条件再次加载页码恢复1，如果这2次页码都是1就不再去触发后面的事件

**Comment by miaoyaoyao** [comment]
这个思路比较有意思，提的也很好，其实我的想法是有一个问题，比如我当前页码在第6页，在搜索时，情况应该是重置当前页码为第1页，然后继续根据当前搜索条件去搜索，是会存在两次请求，提的建议很好，我想下如何解决。可能太久没更新这个插件了，不好意思。

**Comment by zenochan** [comment]
https://github.com/puppet2436/ng.pagination 

fork 了你的代码，做了以下修改，解决了本 issue 中的问题

```
- 解决重复调用 onChange 问题
- 代码重排
- 插件改名为 ng.pagination
- 输入页码跳转只有在敲入回车时才调用 onChange
```

**Comment by miaoyaoyao** [comment]
@puppet2436 挺好的，有时间我也重写了下。也顺带感谢下 @317482454 。

**Comment by miaoyaoyao** [comment]
我已经重写代码并且修复了重复调用问题。如果再有问题，提issue给我。
